<?php
namespace App\Models;

use CodeIgniter\Model;

class LofFundsModel extends Model
{
    protected $table      = 'lof_funds';
    protected $primaryKey = 'id';

    // As in the original TS code, IDs were UUIDs generated by Supabase or custom, 
    // If not auto-increment, we need to handle that or let DB handle it.
    // Supposing UUIDs or string IDs are used:
    protected $useAutoIncrement = true;
    protected $returnType       = 'array';

    // Security: Only allowed fields can be inserted/updated
    protected $allowedFields = [
        'id',
        'code',
        'name',
        'stock_name',
        'price',
        'market_price',
        'net_value',
        'premium_rate',
        'volume',
        'turnover_rate',
        'alert_threshold',
        'last_update',
        'category',
        'purchase_status',
        'purchase_fee',
        'is_deleted'
    ];

    /**
     * Get active funds with optional filtering
     * 
     * @param string $category 
     * @param string $search
     */
    public function getActiveFunds($category = 'all', $search = '')
    {
        $builder = $this->where('is_deleted', false);

        if ($category !== 'all' && $category !== null && $category !== '') {
            $builder->where('category', $category);
        }

        if (!empty($search)) {
            $builder->groupStart()
                ->like('code', $search)
                ->orLike('name', $search)
                ->groupEnd();
        }

        return $builder->orderBy('premium_rate', 'DESC')->findAll();
    }
}
